minio:
  mode: standalone

  rootUser: "minioadmin"
  rootPassword: "minioadmin123"

  persistence:
    enabled: false  # Отключаем PVC для Docker Desktop

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  service:
    type: ClusterIP
    port: 9000

  consoleService:
    type: ClusterIP
    port: 9001

  ingress:
    enabled: false
  consoleIngress:
    enabled: false

  # Добавляем imagePullPolicy
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2024-05-28T17-19-04Z  # более свежая версия
    pullPolicy: IfNotPresent  # Используем локальный образ если есть

  buckets:
    - name: spark-logs
      policy: none
      purge: false
    - name: spark-data
      policy: none
      purge: false
    - name: artifacts
      policy: none
      purge: false

  metrics:
    serviceMonitor:
      enabled: false
