apiVersion: v2
name: argo-workflows
description: Wrapper chart for Argo Workflows.
type: application
version: 0.1.0
appVersion: "v3.5.11"
dependencies:
  - name: argo-workflows
    version: "0.42.3"
    repository: https://argoproj.github.io/argo-helm

argo-workflows:
  images:
    pullPolicy: IfNotPresent
  
  workflow:
    serviceAccount:
      create: true
      name: argo-workflow
    rbac:
      create: true

  controller:
    image:
      tag: v3.5.11
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    metricsConfig:
      enabled: true
    workflowDefaults:
      spec:
        artifactRepositoryRef:
          configMap: artifact-repositories
          key: default-v1
    nodeSelector:
      kubernetes.io/arch: arm64

  server:
    enabled: true
    image:
      tag: v3.5.11
      pullPolicy: IfNotPresent
    serviceType: ClusterIP
    extraArgs:
      - --auth-mode=server
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    ingress:
      enabled: false
    nodeSelector:
      kubernetes.io/arch: arm64

  executor:
    image:
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi

  useStatefulSetFiles: true

artifactRepositoryConfigMap:
  name: artifact-repositories
  data:
    default-v1: |
      s3:
        bucket: spark-logs
        endpoint: minio.minio.svc.cluster.local:9000
        insecure: true
        accessKeySecret:
          name: minio-credentials
          key: rootUser
        secretKeySecret:
          name: minio-credentials
          key: rootPassword
