# argocd/values.yaml
argo-cd:
  global:
    image:
      tag: "v2.11.0"

  configs:
    params:
      server.insecure: "true"
    cm:
      application.resourceTrackingMethod: annotation

  server:
    service:
      type: ClusterIP
    ingress:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  repoServer:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  applicationSet:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  notifications:
    enabled: false

  dex:
    enabled: false

  redis:
    image:
      repository: redis
      tag: "7.0.15-alpine"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi