# argocd/values-prod.yaml
argo-cd:
  global:
    image:
      tag: "v2.11.0"

  configs:
    params:
      server.insecure: "false"  # TLS на ingress
    cm:
      application.resourceTrackingMethod: annotation
      url: https://argocd.example.com

  server:
    replicas: 2
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.example.com
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi

  repoServer:
    replicas: 2
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi

  applicationSet:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  notifications:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  dex:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  redis:
    image:
      repository: redis
      tag: "7.0.15-alpine"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi